# Generated by Django 6.1 on 2026-08-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('RIDDER', 'Ridder'), ('MIDDLEMAN', 'Middleman'), ('ADMIN', 'Admin')], default='BUYER', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
