# Generated by Django 6.1 on 2026-08-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_type_alter_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('RIDER', 'Rider'), ('MIDDLEMAN', 'Middleman'), ('ADMIN', 'Admin ')], default='BUYER', max_length=10),
        ),
    ]
